### ISSUE TITLE
Implementar lista de path relinking separado dos n elite, mantendo individuos sempre diferentes

### ISSUE THREAD

**Issue by thj3a** [GuilhermeCaeiro/trabmh#10]

**Comment by GuilhermeCaeiro** [comment]
Isso foi implementado, mas não devidamente testado, no commit [09442b1](https://github.com/GuilhermeCaeiro/trabmh/commit/09442b1e3eff3afd552a94d15da37bff99302da6). Peço que dê uma verificada, pois ainda falta fazermos uso devido do path relinking, pois o mesmo é executado, mas o resultado ainda não é aproveitado.

Como algo adicional que pode ser feito no âmbito deste issue, poderíamos adicionar uma opção para o usuário escolher qual lista deseja usar para o path relinking: uma própria para isso, ou o elite set.
