### ISSUE TITLE
Verificar se o código hash está funcionando corretamente

### ISSUE THREAD

**Issue by thj3a** [GuilhermeCaeiro/trabmh#12]

**Comment by thj3a** [comment]
Código para testar posteriormente, se for o caso:

def binatodeci(binary): 
   return sum(val*(2**idx) for idx, val in enumerate(reversed(binary)))

**Comment by GuilhermeCaeiro** [comment]
Testei esse código e, assim como um outro método que utilizei anteriormente para converter de binário para decimal, ele falha com sequências binárias muito longas (tamanho 100, por exemplo), produzindo um resultado errado (ou, pelo menos, diferente do esperado, quando comparado com o resultado de ferramentas disponíveis online para esse propósito). Esse presente em sua mensagem também dá erro quando asequência é muito maior, como quando tem 10000 bits ou mais.
