### ISSUE TITLE
Equiparar as implementações dos métodos de cruzamento/seleção/mutação de representação binária para permutação

### ISSUE THREAD

**Issue by thj3a** [GuilhermeCaeiro/trabmh#6]

**Comment by GuilhermeCaeiro** [comment]
O que seria "equiparar" neste caso? Não me recordo deste item. :(

**Comment by thj3a** [comment]
Seria implementar todos os métodos que existem pra binário também pra permutação... Seria implementar o método análogo

**Comment by GuilhermeCaeiro** [comment]
No caso de seleção, os métodos já existentes servem para os dois, assim como no caso de métodos de inicialização. Quanto ao crossover, não creio que seja aplicável (posso estar falando besteira). Mutação, depende do método (por exemplo, os métodos para flipar uma posição seriam análogos).
