### ISSUE TITLE
Implementar nbest com individuos diferentes

### ISSUE THREAD

**Issue by thj3a** [GuilhermeCaeiro/trabmh#7]

**Comment by GuilhermeCaeiro** [comment]
Se entendi corretamente, foi implementado no commit [783cb87](https://github.com/GuilhermeCaeiro/trabmh/commit/783cb874eaa06f06fcdf1eecd4932f168ce9c76c).

**Comment by GuilhermeCaeiro** [comment]
Foi corrigido no commit https://github.com/GuilhermeCaeiro/trabmh/commit/0a2337d834ffa3c827be6462aca4994de35e2b63.
