### ISSUE TITLE
Implementar o tracking de tempo para as soluções

### ISSUE THREAD

**Issue by thj3a** [GuilhermeCaeiro/trabmh#9]

**Comment by GuilhermeCaeiro** [comment]
Poderia especificar do que se trata este issue? Fala só de salvar as mudanças em uma lista ou há algo mais? Se for só salvar as mudanças, está implementado no commit [09442b1](https://github.com/GuilhermeCaeiro/trabmh/commit/09442b1e3eff3afd552a94d15da37bff99302da6).

**Comment by thj3a** [comment]
Esse seria o caso de registrar há quanto tempo/iteracoes não há melhoria... Pq daí dá pra calcular quanto tempo levou pra se chegar até um valor de solução

**Comment by GuilhermeCaeiro** [comment]
O tempo e o número da iteração em que há mudança no "best_sol" são salvos nos atributos "best_sol_change_times" e "best_sol_change_generations" na classe GeneticAlgorithm. A verificação de quanto tempo e iterações tem desde a última alteração é no método [stop_execution na classe GeneticAlgorithm](https://github.com/GuilhermeCaeiro/trabmh/blob/783cb874eaa06f06fcdf1eecd4932f168ce9c76c/genetic_algorithm.py#L175).

**Comment by thj3a** [comment]
Resolvido por 09442b1e3eff3afd552a94d15da37bff99302da6.

**Comment by thj3a** [comment]
Resolvido por 09442b1e3eff3afd552a94d15da37bff99302da6.
